### ISSUE TITLE
signx_tx exception into bip44::Wallet

### ISSUE THREAD

**Issue by ypopovych** [input-output-hk/rust-cardano#166]
Hi.

I use this library via js-cardano-wasm bindings. And found a problem with spend function.

It panics. Seems as a problem inside the "sign_tx" function.

In this call `.account(self.derivation_scheme, addressing.account.get_scheme_value())`

Function works fine if you replace it with `.account(self.derivation_scheme, addressing.account.get_account_number())`.

I can't tell if this fix is good, but transaction, generated with fixed function can be sent to the network and works fine (at least for (0, 0, 0) addressing)

**Comment by NicolasDP** [comment]
thanks for the report, I'll have a look

**Comment by NicolasDP** [comment]
thanks for reporting the issue @ypopovych 

it was a problem, the addressing is (and should be valid) the issue came when deriving the account level. The assert was the wrong way around. I removed them in PR #167 because they are not needed, by construction the Addressing is valid.

I'll update the js-cardano-wasm shortly
