### ISSUE TITLE
remove cargo Lock from the repo

### ISSUE THREAD

**Issue by NicolasDP** [input-output-hk/rust-cardano#239]
While this makes sense for an executable, for the library we do not want to tie to specific points.

Depends on #238

**Comment by jleni** [comment]
I kind of disagree here. Libraries also have upstream dependencies. 
Without a cargo.lock any incompatible changes in upstream dependencies would break things. 
Maybe I am missing some details?

**Comment by vincenthz** [comment]
We're still open to discussion, but the basic ideas behind this is:

* Each application will chose their own dependencies on an application-by-application case
* The SDK part (cardano, cardano-storage, cardano-network, ..) is really striving to have minimum dependencies as possible; we'll very likely will remove things, than add dependencies in the future.
* With less dependencies, we should lower the incidences of incompatible changes in upstream dependencies
* If upstream dependencies have incompatible changes, it's very likely we need to catch up anyway; maybe having to do it sooner than later is not a bad plan

**Comment by jleni** [comment]
In general terms, I would assume any SDK I rely on has gone through integration testing and has been verified to work with a set of upstream dependencies. SDKs promise both reliable interfaces and behavior. If dependencies are not well defined, the problem is passed to every single application that depends on the SDK. This means a lot of trouble, specially to anyone that has experienced configuration management issues.
Moreover, I assume that the SDK will be published as a crate. Something standard in the rust world. And crates are very clear about their requirements at the moment of being published.

**Comment by vincenthz** [comment]
The dependencies semantics defined in Cargo.toml is independent from the Cargo.lock which pin down specific dependencies. We're not planning to remove the Cargo.toml or not maintain the dependencies properly.

**Comment by jleni** [comment]
Yes, I get that. Without the lock, continuous integration results are not really reproducible, however, locking can result in multiple different copies being used, etc.

I guess that you are not planning to release any binaries in this project, just source code, so I see why it makes sense. I suppose that executables/deliverables in binary form will then be moved out from this project, right?

**Comment by vincenthz** [comment]
correct. we already have https://github.com/input-output-hk/cardano-cli as our first real application where we'll have the right thing pin down; more repositories will follow, likely in the same spirit.
